# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoFile.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fProtoFile.proto\"\t\n\x07Request\"\x1a\n\x08Response\x12\x0e\n\x06phrase\x18\x01 \x01(\t2(\n\x07Service\x12\x1d\n\x06Phrase\x12\x08.Request\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProtoFile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=19
  _globals['_REQUEST']._serialized_end=28
  _globals['_RESPONSE']._serialized_start=30
  _globals['_RESPONSE']._serialized_end=56
  _globals['_SERVICE']._serialized_start=58
  _globals['_SERVICE']._serialized_end=98
# @@protoc_insertion_point(module_scope)
