# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lizGenerator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12lizGenerator.proto\x12\x03liz\"\t\n\x07Request\"\x1a\n\x08Response\x12\x0e\n\x06phrase\x18\x01 \x01(\t20\n\x07Service\x12%\n\x06Phrase\x12\x0c.liz.Request\x1a\r.liz.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lizGenerator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=27
  _globals['_REQUEST']._serialized_end=36
  _globals['_RESPONSE']._serialized_start=38
  _globals['_RESPONSE']._serialized_end=64
  _globals['_SERVICE']._serialized_start=66
  _globals['_SERVICE']._serialized_end=114
# @@protoc_insertion_point(module_scope)
