// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package russvslizards.server;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_russvslizards_server_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_russvslizards_server_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_russvslizards_server_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_russvslizards_server_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_russvslizards_server_RequestV_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_russvslizards_server_RequestV_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_russvslizards_server_ResponseV_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_russvslizards_server_ResponseV_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013proto.proto\022\024russvslizards.server\"\t\n\007R" +
      "equest\"\032\n\010Response\022\016\n\006phrase\030\001 \001(\t\"\031\n\010Re" +
      "questV\022\r\n\005vibor\030\001 \001(\003\"\013\n\tResponseV2R\n\007Se" +
      "rvice\022G\n\006Phrase\022\035.russvslizards.server.R" +
      "equest\032\036.russvslizards.server.Response2R" +
      "\n\006Choise\022H\n\005Vibor\022\036.russvslizards.server" +
      ".RequestV\032\037.russvslizards.server.Respons" +
      "eVB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_russvslizards_server_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_russvslizards_server_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_russvslizards_server_Request_descriptor,
        new java.lang.String[] { });
    internal_static_russvslizards_server_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_russvslizards_server_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_russvslizards_server_Response_descriptor,
        new java.lang.String[] { "Phrase", });
    internal_static_russvslizards_server_RequestV_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_russvslizards_server_RequestV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_russvslizards_server_RequestV_descriptor,
        new java.lang.String[] { "Vibor", });
    internal_static_russvslizards_server_ResponseV_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_russvslizards_server_ResponseV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_russvslizards_server_ResponseV_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
