// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package russvslizards.server;

public interface RequestVOrBuilder extends
    // @@protoc_insertion_point(interface_extends:russvslizards.server.RequestV)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 vibor = 1;</code>
   * @return The vibor.
   */
  long getVibor();
}
