// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package russvslizards.server;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:russvslizards.server.Request)
    com.google.protobuf.MessageOrBuilder {
}
