// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package russvslizards.server;

public interface ResponseVOrBuilder extends
    // @@protoc_insertion_point(interface_extends:russvslizards.server.ResponseV)
    com.google.protobuf.MessageOrBuilder {
}
