// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package russvslizards.server;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:russvslizards.server.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phrase = 1;</code>
   * @return The phrase.
   */
  java.lang.String getPhrase();
  /**
   * <code>string phrase = 1;</code>
   * @return The bytes for phrase.
   */
  com.google.protobuf.ByteString
      getPhraseBytes();
}
